// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmv3A_t2MGAJ_KegV6wBrz7dwNO4tHzOc',
    appId: '1:269354342254:web:006afc1800f3d015bd937f',
    messagingSenderId: '269354342254',
    projectId: 'fakahani-e-commerce',
    authDomain: 'fakahani-e-commerce.firebaseapp.com',
    storageBucket: 'fakahani-e-commerce.firebasestorage.app',
    measurementId: 'G-67Y22MPEG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOBaJ5VPFwGDDr0wPr8xvRddMOKfR-7qM',
    appId: '1:269354342254:android:be6d1d61ede2d8b1bd937f',
    messagingSenderId: '269354342254',
    projectId: 'fakahani-e-commerce',
    storageBucket: 'fakahani-e-commerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-59ZEb0dGD3umkzdLvTmIpWO0A75tJAY',
    appId: '1:269354342254:ios:4e14c7e45ae41193bd937f',
    messagingSenderId: '269354342254',
    projectId: 'fakahani-e-commerce',
    storageBucket: 'fakahani-e-commerce.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );
}
